# Generated by Django 2.0 on 2017-12-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskNumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=24)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Risk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='riskcurrencyfield',
            name='risk',
        ),
        migrations.AlterField(
            model_name='riskdatetimefield',
            name='value',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='risktextfield',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='RiskCurrencyField',
        ),
    ]
