# Generated by Django 2.0 on 2017-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20171207_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdatetimefield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskdatetimefields', to='risks.Risk'),
        ),
        migrations.AlterField(
            model_name='risknumberfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risknumberfields', to='risks.Risk'),
        ),
        migrations.AlterField(
            model_name='risktextfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risktextfields', to='risks.Risk'),
        ),
    ]
