# Generated by Django 2.0 on 2017-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskenumfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskenumfield',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
