# Generated by Django 2.0 on 2017-12-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20171208_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdatetimefield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimefields', to='risks.Risk'),
        ),
        migrations.AlterField(
            model_name='risknumberfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numberfields', to='risks.Risk'),
        ),
        migrations.AlterField(
            model_name='risktextfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textfields', to='risks.Risk'),
        ),
    ]
