# Generated by Django 2.0 on 2017-12-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20171212_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdatetimefield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='riskenumfield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='risknumberfield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='risktextfield',
            name='value',
        ),
    ]
