# Generated by Django 2.0 on 2017-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20171213_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdatetimefield',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='riskenumfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='risknumberfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='risktextfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
